project/cart/urls.py
from django.urls import path

from .views import (
    cart_add,
    cart_detail,
    remove_product,
    add_quantity,
    take_quantity,
    order_redirect,
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('addq/<int:product_id>', add_quantity, name='add_quantity'),
    path('remove/<int:product_id>', remove_product, name='remove_product'),
    path('removeq/<int:product_id>', take_quantity, name='take_quantity'),
    path('order_redirect', order_redirect, name='order_redirect')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# image = models.ImageField(upload_to=get_upload_path, blank=True, verbose_name='Изображение')

project/shop/urls.py
from django.urls import path, re_path

from .views import (
    Index,
    ProductDetail,
    SearchView,
    get_category

)


app_name = 'shop'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('catalogue/product/<int:id>', ProductDetail.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('catalogue/category/<int:id>', get_category, name='get_category'),

]

project/shop/models.py
from django.db import models
from os.path import join
from django.shortcuts import reverse
from django.template.defaultfilters import slugify as django_slugify


alphabet = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i',
            'й': 'j', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't',
            'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ы': 'i', 'э': 'e', 'ю': 'yu',
            'я': 'ya'}


def slugify(s):
    """
    Overriding django slugify that allows to use russian words as well.
    """
    return django_slugify(''.join(alphabet.get(w, w) for w in s[0].lower()))


def get_upload_path(instance, filename):
    filename = slugify(filename.split('.'[0])) + '.' + filename.split('.')[1]
    return join('images/', filename)


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название категории')
    slug = models.SlugField(max_length=100, db_index=True, verbose_name='Слаг')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=get_upload_path, blank=True)

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['name']

    class Meta:
        ordering = ('name',)
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):

    name = models.CharField(max_length=100, db_index=True, verbose_name='Наименование товара')
    slug = models.SlugField(max_length=100, db_index=True, verbose_name='Слаг')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.PositiveIntegerField(verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    stock = models.PositiveIntegerField(verbose_name='В наличие штук')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Изменено')
    image = models.ImageField(upload_to=get_upload_path, blank=True, verbose_name='Изображение')
    tags = models.ManyToManyField(Category, 'Теги')

    class Meta:
        ordering = ('name',)
        index_together =(('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id])


class ProductImages(models.Model):
    iproduct = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_upload_path, blank=True, verbose_name='')

    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'

    def __str__(self):
        return ''


class Promotion(models.Model):
    proms = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, verbose_name='Товар',
                              related_name='promo')

    class Meta:
        verbose_name = 'Акция'
        verbose_name_plural = 'Акции'

    def __str__(self):
        return str(self.pk)

project/shop/forms.py
from django import forms
from .models import Product


choices = [
    (0, 'Сортировка'),
    (1, 'Цена по возрастанию'),
    (2, 'Цена по убыванию'),
    (3, 'Порядок А-Я'),
    (4, 'Порядок Я-А')
]


class SortForm(forms.Form):
    gte = forms.IntegerField(min_value=0, label='От', widget=forms.NumberInput(), required=False)
    lte = forms.IntegerField(min_value=0, label='До', widget=forms.NumberInput(), required=False)
    sort = forms.TypedChoiceField(label='',
                                  choices=choices,
                                  widget=forms.Select(
                                    attrs={
                                        'class': 'select-form',
                                        'align': 'center',
                                    }
                                  ), required=False)

# class PriceForm(forms.Form):
#     gte = forms.IntegerField(min_value=0, label='От', widget=forms.NumberInput(), required=False)
#     lte = forms.IntegerField(min_value=0, label='До', widget=forms.NumberInput, required=False)

project/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Promotion, ProductImages
from django.views.generic import View, DetailView, ListView
from os.path import join
from project.settings import BASE_DIR
from .forms import SortForm
from django.db.models import *
from django.shortcuts import redirect
from .models import Category


class Index(ListView):
    template_name = 'index.html'
    context_object_name = 'promos'

    def get_queryset(self):
        self.request.session['q'] = ''
        promos = Promotion.objects.all()
        return promos


# def index(request):
#     promos = Promotion.objects.all()
#     context = {
#         'promos': promos,
#     }
#     request.session['q'] = ''
#
#     return render(request, 'index.html', context=context)


def sort_price(request, got_items=None):  # Говнокод | разобрать
    i = request.session['i']
    lte = request.session['lte']
    gte = request.session['gte']

    if got_items is not None:  # Если получает query
        obj = got_items
        if gte and lte:
            request.session['lte'] = lte
            request.session['gte'] = gte
            got_items = obj.filter(price__gte=gte, price__lte=lte)
        elif gte:
            request.session['gte'] = gte
            got_items = obj.filter(price__gte=gte)
        elif lte:
            request.session['lte'] = lte
            got_items = obj.filter(price__lte=lte)
        else:
            got_items = obj

        if i == '1':
            products = got_items.order_by('price')
        elif i == '2':
            products = got_items.order_by('-price')
        elif i == '3':
            products = got_items.order_by('name')
        elif i == '4':
            products = got_items.order_by('-name')
        else:
            products = got_items
    else:
        if request.session['id']:
            id = request.session['id']
            if gte and lte:
                request.session['lte'] = lte
                request.session['gte'] = gte
                got_items = Product.objects.filter(tags=id, price__gte=gte, price__lte=lte)
            elif gte:
                request.session['gte'] = gte
                got_items = Product.objects.filter(tags=id, price__gte=gte)
            elif lte:
                request.session['lte'] = lte
                got_items = Product.objects.filter(tags=id, price__lte=lte)
            else:
                got_items = Product.objects.filter(tags=id)
        else:
            if gte and lte:
                request.session['lte'] = lte
                request.session['gte'] = gte
                got_items = Product.objects.filter(price__gte=gte, price__lte=lte)
            elif gte:
                request.session['gte'] = gte
                got_items = Product.objects.filter(price__gte=gte)
            elif lte:
                request.session['lte'] = lte
                got_items = Product.objects.filter(price__lte=lte)
            else:
                got_items = Product.objects.all()

        if i == '1':
            products = got_items.order_by('price')
        elif i == '2':
            products = got_items.order_by('-price')
        elif i == '3':
            products = got_items.order_by('name')
        elif i == '4':
            products = got_items.order_by('-name')
        else:
            products = got_items

    return products


def get_category(request, id):
    if request.method == 'GET':
        request.session['i'] = request.GET.get('sort')
        request.session['gte'] = request.GET.get('gte')
        request.session['lte'] = request.GET.get('lte')
        request.session['id'] = id
        sort_form = SortForm(request.GET)
        if not sort_form.is_valid():
            return redirect('shop:get_category', id=id)
        else:  # Чтобы значение оставалось после отправки формы
            sort_form.cleaned_data['gte'] = request.session['gte']
            sort_form.cleaned_data['lte'] = request.session['lte']

        products = sort_price(request)

        sort_form = SortForm(request.GET)
        context = {
            'products': products,
            'sort_form': sort_form,
        }
        return render(request, 'product/category.html', context)


class ProductDetail(View):  # Можно использовать, когда def func(request, data):
    # return render(request, 'tmplt.path', context) 
    def get(self, request, id):
        product = Product.objects.filter(id=id, available=True)[0]
        product_images = ProductImages.objects.filter(iproduct=product)
        return render(request, 'product/detail.html', context={'product': product, 'product_images': product_images})


# def product_detail(request, id):
#     product = get_object_or_404(Product, id=id, available=True)
#     context = {
#         'product': product,
#     }
#
#     return render(request, 'product/detail.html', context=context)


class SearchView(ListView):
    template_name = join(BASE_DIR, 'shop/templates/product/category.html')

    # context_object_name = 'products'

    def get_queryset(self):  # поиск, квери кидает в сессию['q']
        if not self.request.session['q']:
            self.request.session['i'] = self.request.GET.get('sort')

            sort_form = SortForm(self.request.GET)

            query = self.request.GET.get('q')  # Поиск

            if query is None:
                got_items = ProductImages.iproduct.objects.filter(available=True)
                products = sort_price(self.request, got_items)

                context = {
                    'products': products,
                    'sort_form': sort_form,
                }

                return context
            else:
                got_items = Product.objects.filter(
                    Q(name__icontains=query) | Q(id__icontains=query)
                )

                products = got_items

                agg_max = products.aggregate(Max('price'))['price__max']
                agg_min = products.aggregate(Min('price'))['price__min']

                context = {
                    'products': products,
                    'sort_form': sort_form,
                }
                self.request.session['q'] = query
                return context
        else:
            new_query = self.request.GET.get('q')

            if self.request.session['q'] != new_query and new_query is not None:
                if self.request.method == 'GET':
                    self.request.session['i'] = self.request.GET.get('sort')
                    price_form = SortForm(self.request.GET)
                    if not price_form.is_valid():
                        return redirect('/')
                    else:  # Чтобы значение оставалось после отправки формы
                        price_form.cleaned_data['gte'] = self.request.session['gte']
                        price_form.cleaned_data['lte'] = self.request.session['lte']

                    sort_form = SortForm(self.request.GET)

                # Поиск

                query = new_query
                got_items = Product.objects.filter(
                    Q(name__icontains=query) | Q(id__icontains=query)
                )

                products = sort_price(self.request, got_items)
                context = {
                    'products': products,
                    'sort_form': sort_form,
                    'price_form': price_form
                }
                self.request.session['q'] = query
                return context
            else:
                if self.request.method == 'GET':
                    self.request.session['i'] = self.request.GET.get('sort')
                    self.request.session['gte'] = self.request.GET.get('gte')
                    self.request.session['lte'] = self.request.GET.get('lte')

                    sort_form = SortForm(self.request.GET)

                    if not sort_form.is_valid():
                        return redirect('/')
                    else:  # Чтобы значение оставалось после отправки формы
                        sort_form.cleaned_data['gte'] = self.request.session['gte']
                        sort_form.cleaned_data['lte'] = self.request.session['lte']

                # Поиск

                query = self.request.session['q']
                got_items = Product.objects.filter(
                    Q(name__icontains=query) | Q(id__icontains=query)
                )

                products = sort_price(self.request, got_items)

                self.request.session['gte'] = self.request.GET.get('gte')
                self.request.session['lte'] = self.request.GET.get('lte')

                context = {
                    'products': products,
                    'sort_form': sort_form,
                }
                return context

project/shop/templates/product/category.html
{% extends 'base.html' %}

{% block content %}
{% if object_list %}
    {% with object_list.products as products %}
    {% with object_list.sort_form as sort_form %}
    {% with object_list.price_form as price_form %}

    <section class="cont">
        <div class="cont-sort">
        </div>
        <div class="filt-cont">
            <div class="flex-col-3">
                {% for product in products %}
                    <div class="card">
                        <a href="{% url 'shop:product_detail' product.pk %}">
                        <img class="card-img-top" src="{{ product.image.url }}" alt="изображение продукта">
                        <div class="card-body">
                            <p class="card-text">{{product.name | truncatechars:100}}</p>
                        </div>
                        </a>
                        <p class="card-price">{{product.price}} ₽</p>
                    </div>
                {% endfor %}
            </div>
            <div class="block-filt">
                <div class="top-part">
                    <p>Цена</p>
                </div>
                <div class="bot-part">
                    <form>
                    {{ sort_form }}
                    <button type="submit">
                        Показать
                    </button>
                    <button type="reset">
                        Отчистить
                    </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-4">

        </div>
      </div>
    </section>
    {% endwith %}
    {% endwith %}
    {% endwith %}
{% else %}
    <section class="cont">
        <div class="cont-sort">
        </div>
        <div class="filt-cont">
            <div class="flex-col-3">
                {% for product in products %}
                    <div class="card">
                        <a href="{% url 'shop:product_detail' product.pk %}">
                        <img class="card-img-top" src="{{ product.image.url }}" alt="изображение продукта">
                        <div class="card-body">
                            <p class="card-text">{{product.name | truncatechars:100}}</p>
                        </div>
                        </a>
                        <p class="card-price">{{product.price}} ₽</p>
                    </div>
                {% endfor %}
            </div>
            <div class="block-filt">
                <div class="top-part">
                    <p>Цена</p>
                </div>
                <form>
                <div class="mid-part">
                    {{ price_form }}
                    <p>₽</p>
                </div>
                <div class="bot-part">
                    {{ sort_form }}
                    <button type="submit">
                        Показать
                    </button>
                    <button type="reset">
                        Отчистить
                    </button>

                </div>
                </form>
            </div>
        </div>

        <div class="col-sm-4">
        </div>
      </div>
    </section>
{% endif %}
{% endblock %}

project/shop/templates/product/detail.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="content">
        <div class="content-top">
            <div class="left-img">
                {% for i in product_images %}
                <img src="{{i.image.url}}">
                {% endfor %}
            </div>
            <div class="img">
                <img src="{{product.image.url}}">
            </div>
            <div class="right-info">
                <div class="upper-block">
                    <div class="upper-block-content">
                        <h3>{{product.name}}</h3>
                        <p>{{product.price}} ₽</p>
                        <form class="upper-block-content-form" action="{% url 'cart:cart_add' product.id %}">
                            <input type="submit" value="Добавить в корзину">
                        </form>
                    </div>
                </div>
                <div class="lower-block">
                    <div class="lower-block-content">
                        <p>Название: A.I.Channel </p>
                        <p>Персонаж: Kizuna Ai</p>
                        <p>Тип фигурки: Модель в сборе</p>
                        <p>Материал: ПВХ, пластмасса</p>
                        <p>Высота: 240 мм</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="description">
            <div class="description-content">
                <h6>Описание</h6>
                <p>{{product.description}}</p>
            </div>
        </div>
        <div class="reviews">
            <div class="reviews-content">
                <h6>Отзывы</h6>
                <div class="col-12">
                    <div class="col-1">
                        <img src="{{product.image.url}}">
                    </div>
                    <div class="col-5">
                        <p>Имя пользователя</p>
                    </div>
                    <div class="col-6">
                        <div class="stars">
                          <div class="star"></div>
                          <div class="star"></div>
                          <div class="star"></div>
                          <div class="star"></div>
                          <div class="star"></div>
                        </div>
                        <div class="date">
                            <p>28/07/2020</p>
                        </div></div>
                </div>
                <div class="p">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet, nisl vel suscipit euismod, purus arcu feugiat tellus, quis gravida lorem ipsum non metus. Integer risus risus, pulvinar in maximus sit amet, posuere sed mi. Morbi luctus volutpat suscipit. Nam et nunc cursus, ullamcorper ex aliquam, accumsan ex. Nulla est est, suscipit et arcu ac, lobortis mattis tellus. In euismod aliquam odio eget vestibulum. Ut risus ligula, convallis porttitor auctor sed, finibus eu sem. Suspendisse et sapien non quam gravida placerat. Donec commodo, odio ac fermentum efficitur, libero diam feugiat tellus, vel imperdiet ex mi vel nunc.</p>
                </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}