project/cart/urls.py
from django.urls import path

from .views import (
    cart_add,
    cart_detail,
    remove_product,
    add_quantity,
    take_quantity,
    order_redirect,
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('addq/<int:product_id>', add_quantity, name='add_quantity'),
    path('remove/<int:product_id>', remove_product, name='remove_product'),
    path('removeq/<int:product_id>', take_quantity, name='take_quantity'),
    path('order_redirect', order_redirect, name='order_redirect')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# image = models.ImageField(upload_to=get_upload_path, blank=True, verbose_name='Изображение')

project/cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from pytz import unicode


class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)


class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)


class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

project/cart/forms.py
from django import forms
from django.forms import ModelForm
from .models import Item


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='', choices=PRODUCT_QUANTITY_CHOICES, coerce=int,
    widget=forms.Select(
        attrs={'class': 'form-control'}
        ))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class Quantity(ModelForm):
    class Meta:
        model = Item
        fields = ('quantity',)

project/cart/views.py
"""from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.success(request, 'Удалено')
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})"""
from django.contrib import messages
from cart.cart import Cart
from shop.models import Product
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CartAddProductForm, Quantity
from django.http import HttpResponse


def test(response):
    for i in response.cookies:
        print('<h2>{}</h2>'.format(i))


# Rewrite using CBV

def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return redirect(to='cart:cart_detail')


def add_quantity(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return redirect(to='cart:cart_detail')


def take_quantity(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.take(product)
    return redirect(to='cart:cart_detail')


def remove_product(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    return render(request, 'cart_detail.html', context={'cart': Cart(request)})


def order_redirect(request):
    return redirect('order:make_order')

project/cart/templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section>
    <div class="cart-content">
        <h3>Корзина</h3>
        <div class="cart-content-cover">
            <div class="left-side-content">
                {% for item in cart %}
                    {% with product=item.product  %}
                    <div class="cart-line" cellspacing="0">
                        <div class="cart-img">
                            <a href="{{product.get_absolute_url}}">
                                <img class="cart-img" src="{{ product.image.url }}" alt="...">
                            </a>
                        </div>
                        <div class="cart-description">
                            <p class="cart-name">{{ product.name }}</p>
                            <p class="cart-price">
                                {{ item.total_price }} ₽
                            </p>
                            <p class="cart-id">
                                Артикул: {{ product.id }}
                            </p>
                        </div>
                        <div class="cart-amount">
                            <div class="cart-amount-inner">
                                <div class="quantity">
                                <form action="{% url 'cart:take_quantity' product.id %}">
                                    {% csrf_token %}
                                    <input type="submit" value="-" class="take_quantity">
                               </form>
                                <div class="quantity_out">{{ item.quantity }}</div>
                                <form method="POST" action="{% url 'cart:add_quantity' product.id %}">
                                    {% csrf_token %}
                                    <input type="submit" name="add_quantity" value="+" class="add_quantity"></inputbutton>
                                </form>
                                </div>
                                <p>
                                    {% if item.quantity > 1 %}
                                        {{ product.price }} ₽ за шт.
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                        <div class="cart-remove">
                                <a href="{% url 'cart:remove_product' product.id %}">
                                    <img class="cart-remove-img" src="/static/images/exit.svg">
                                </a>
                        </div>
                    </div>
                    {% endwith %}
                {% endfor %}
        </div>
        <div class="buy-menu">
            <div class="buy-menu-content">
                <p>Итого</p>
                <hr>
                <div class="payment-price">
                    <div class="payment-price-first">
                        <p>Всего:</p>
                        <p>{{ cart.get_total_price }} ₽</p>
                    </div>
                    <div class="payment-price-second">
                        <p>Доставка: </p>
                        <p>150 ₽</p>
                    </div>
                </div>
                <form class="shipment">
                    <input value="Стандартная доставка">
                </form>
                <form>
                    <input class="payment-proceed" type="submit" value="Оплатить">
                </form>
                <p class="last-p">Мы принимаем:</p>
                <img src="/static/images/cards.svg">
            </div>
        </div>

    </div>
</section>

{% endblock %}